# Generated by Django 4.1.1 on 2022-09-28 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_cart_customer_remove_cart_reception_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_item', to='store.cart'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_item', to='store.cart'),
        ),
    ]
