# Generated by Django 4.1.1 on 2022-09-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cart_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductItem',
            new_name='CartItem',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductAndService',
        ),
        migrations.AddField(
            model_name='category',
            name='service_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ServiceItem',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
