# Generated by Django 4.1.1 on 2022-09-29 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_reception_cart_cart_reception'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='reception',
        ),
        migrations.AddField(
            model_name='reception',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.cart'),
        ),
    ]
