# Generated by Django 4.1.1 on 2022-09-29 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_cart_reception_reception_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.cart'),
        ),
    ]
